from django.urls import path
from .views import *
from rest_framework_simplejwt.views import TokenRefreshView
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path("products/", SupplierProductListCreateView.as_view(), name="product-list-create"),
    path("products/<int:pk>/", SupplierProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/status/", ProductStatusToggleView.as_view(), name="product-status-toggle"),
    path("link/send/", SendLinkRequestView.as_view(), name="send-link"),
    path("links/", SupplierLinkListView.as_view()),
    path("link/<int:link_id>/", UnlinkView.as_view()),
    path("link/<int:link_id>/accept/", AcceptLinkView.as_view()),
    path("link/<int:link_id>/reject/", RejectLinkView.as_view()),
    path("link/<int:link_id>/block/", BlockLinkView.as_view()),
    path("link/<int:link_id>/unblock/", UnblockLinkView.as_view()),
    path("suppliers/", AllSuppliersView.as_view(), name="all-suppliers"),
    path("consumer/links/", ConsumerLinkListView.as_view(), name="consumer-links"),
    path("supplier/<int:supplier_id>/catalog/", SupplierCatalogView.as_view(), name="supplier-catalog"),
    path("cart/add/", CartAddView.as_view(), name="cart-add"),
    path("cart/", CartListView.as_view(), name="cart-list"),
    path("cart/<int:item_id>/", CartItemUpdateDeleteView.as_view(), name="cart-item"),
    path("orders/checkout/", CheckoutView.as_view(), name="checkout"),
    path("orders/my/", MyOrdersView.as_view(), name="my-orders"),
    path("orders/supplier/", SupplierOrdersView.as_view(), name="supplier-orders"),
    path("chat/<int:partner_id>/", ChatHistoryView.as_view(), name="chat-history"),
    path("chat/<int:supplier_id>/send/", SendMessageView.as_view(), name="chat-send"),
    path("orders/<int:order_id>/accept/", SupplierAcceptOrderView.as_view(), name="order-accept"),
    path("orders/<int:order_id>/reject/", SupplierRejectOrderView.as_view(), name="order-reject"),
    path("complaints/<int:order_id>/create/", CreateComplaintView.as_view(), name="complaint-create"),
    path("complaints/supplier/", SupplierComplaintListView.as_view(), name="complaints-supplier"),
    path("complaints/<int:complaint_id>/resolve/", SupplierResolveComplaintView.as_view(), name="complaint-resolve"),
    path("complaints/<int:complaint_id>/reject/", SupplierRejectComplaintView.as_view(), name="complaint-reject"),
    path("complaints/<int:complaint_id>/escalate/", EscalateComplaintView.as_view(), name="complaint-escalate"),
    path("orders/<int:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/stats/", ConsumerOrderStatsView.as_view(), name="order-stats"),
    path("orders/supplier/stats/", SupplierOrderStatsView.as_view(), name="supplier-order-stats"),
    path("orders/<int:order_id>/deliver/", SupplierDeliverOrderView.as_view(), name="order-deliver"),
    path("complaints/my/", ConsumerComplaintListView.as_view(), name="complaints-my"),
    path("search/", GlobalSearchView.as_view(), name="global-search"),
    path("company/unassigned/", UnassignedUsersView.as_view()),
    path("company/employees/", CompanyEmployeesView.as_view()),
    path("company/assign/", AssignEmployeeView.as_view()),
    path("company/remove/", RemoveEmployeeView.as_view()),
    path("account/delete/", DeleteOwnerAccountView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("canned-replies/", CannedReplyListView.as_view(), name="canned-replies-list"),
    path("canned-replies/<int:pk>/", CannedReplyDetailView.as_view(), name="canned-reply-detail"),
]
