# Generated by Django 4.2.17 on 2025-11-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_linkrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="linkrequest",
            unique_together={("supplier", "consumer")},
        ),
    ]
