# Generated by Django 4.2.17 on 2025-11-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_company_remove_supplierprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
