# Generated by Django 4.2.17 on 2025-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_message_attachment_message_attachment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_option",
            field=models.CharField(
                choices=[
                    ("delivery", "Delivery"),
                    ("pickup", "Pickup"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lead_time_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of days for order fulfillment"
            ),
        ),
    ]
