# Generated by Django 4.2.17 on 2025-10-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_youtubevideo_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
